In [6]:
import numpy as np

In [7]:



class Layer:

    def relu(self,X):
        return np.maximum(0,X)
    
    def linear(self,X):
        return X
    
    def sigmoid(self,X):
        return 1/(1 + np.exp(-X))

    def __init__(self,unit_num,act_func,input_size) -> None:
        
        self.input_size = input_size
        self.unit_num = unit_num
        self.act_func = act_func
        self.weights = np.random.rand(unit_num,input_size)*0.1
        self.bias = np.zeros((unit_num,1))
        print(self.weights)
        print(self.weights.shape)


    def forward_prop(self,inp):

        

        if self.act_func == "sigmoid":

            
            return self.sigmoid(np.dot(self.weights,inp) + self.bias)
        
        elif self.act_func == "relu":

            return self.relu(np.dot(self.weights,inp) + self.bias)
        

    def __str__(self) -> str:
        return f"Layer with {self.unit_num} units and {self.act_func} activation function."
        
        


        

In [8]:
class NN:

    def __init__(self) -> None:
        self.layers = []
        return None
    def add_layer(self,input_size,activation_function,layer_size):

        new_layer = Layer(unit_num=layer_size,act_func = activation_function,input_size=input_size)
        self.layers.append(new_layer)
        return None
    





In [9]:
deneme = NN()

In [10]:
deneme.add_layer(input_size=3,activation_function="sigmoid",layer_size=5)

[[0.06892208 0.07936875 0.05119922]
 [0.02798635 0.09914478 0.04676236]
 [0.02351678 0.00071431 0.06197819]
 [0.09078899 0.04657907 0.07354136]
 [0.00573837 0.09346385 0.02779369]]
(5, 3)
