In [5]:
import numpy as np

In [120]:
class Layer:

    def relu(self,X):
        return np.maximum(0,X)
    
    def linear(self,X):
        return X
    
    def sigmoid(self,X):
        return 1/(1 + np.exp(-X))

    def __init__(self,unit_num,act_func,input_size) -> None:
        
        self.input_size = input_size
        self.unit_num = unit_num
        self.act_func = act_func
        self.weights = np.random.rand(unit_num,input_size)*0.1
        self.bias = np.zeros((unit_num,1))
        



    def forward_prop(self,inp):
        if self.act_func == "sigmoid":
            return self.sigmoid(np.dot(self.weights,inp) + self.bias)
        
        elif self.act_func == "relu":
            return self.relu(np.dot(self.weights,inp) + self.bias)
        

    def __str__(self) -> str:
        return f"Layer with {self.unit_num} units and {self.act_func} activation function."
        
        


        

In [136]:
class NN:

    def __init__(self) -> None:
        self.layers = []
        return None
    def add_layer(self,input_size,activation_function,layer_size):

        if (len(self.layers) == 0) or (input_size == self.layers[-1].unit_num):
            new_layer = Layer(unit_num=layer_size,act_func = activation_function,input_size=input_size)
            self.layers.append(new_layer)
            print("Added a layer!")
        else:
            raise Exception("Input Size don't match with the last layer's output size!")



        return None
    
    def __str__(self) -> str:

        print(f"Neural Network with {len(self.layers)} layers.")
        for lay in self.layers:
            print(lay)
        
        return ""


    def forward_propagation(self,X):
        output = self.layers[0].forward_prop(X)

        for i in range(1,len(self.layers)):
            output = self.layers[i].forward_prop(output)
            print(f"Output of layer {i+1}:\n{output}")


        return output


In [140]:
deneme = NN()

In [141]:
deneme.add_layer(input_size=3,activation_function="sigmoid",layer_size=25)
deneme.add_layer(input_size=25,activation_function="sigmoid",layer_size=10)
deneme.add_layer(input_size=10,activation_function="relu",layer_size=5)
deneme.add_layer(input_size=5,activation_function="sigmoid",layer_size=1)

Added a layer!
Added a layer!
Added a layer!
Added a layer!


In [142]:
X = np.array([[2],[3],[4]])

In [143]:
deneme.forward_propagation(X)

Output of layer 2:
[[0.70151526]
 [0.69076235]
 [0.67592014]
 [0.68351347]
 [0.67476582]
 [0.70419903]
 [0.69319129]
 [0.66477722]
 [0.69425241]
 [0.70585335]]
Output of layer 3:
[[0.34954889]
 [0.35000619]
 [0.38429986]
 [0.32785115]
 [0.41407692]]
Output of layer 4:
[[0.52277131]]


array([[0.52277131]])